server:
  tomcat:
    max-connections: 8000
  servlet:
    context-path: /community


#数据库配置
spring:
  mail:
    host: smtp.163.com
    port: 465
    username: zhangyu_ayao@163.com
    password: CLKMYDLNIACNNLJM
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 11
    host: localhost
    port: 6379


  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: hsp

  #模板引擎配置
  thymeleaf:
    encoding: UTF-8
    #suffix: .html  默认后缀
    #prefix: classpath:/templates/  默认前缀
    cache: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhangyu.community.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#logging:
  file:
    name: logs/lab.log
  level:
    com:
      zhangyu:
        community: debug

# community
community:
  path:
    domain: http://localhost:8080
    upload: C:/Users/bytedance/Documents/header

